### PR TITLE
fix typing tip view overlapping message bubble

### PR DESCRIPTION
**Pull request by lhr000lhrmega**
What's in this pull request?
fix 
typing-view-overlapping-message-bubble 
https://issues.developers.mega.co.nz/issues/14565

### CODE REVIEW

**Comment by jnavarrom** [comment]
It seems that this fix would only be necessary for devices that do not have a safe area.

@javitrujillo  can you check this? I think we removed this resizing because it caused crashes when updating the collection view while making this resizing

**Comment by javitrujillo** [comment]
There were a strong reason not to to this, probably a crash related with two simultaneous reloads of the collection view, but I cannot reproduce them now. I will continue investigating.

**Comment by jnavarrom** [comment]
@lhr000lhrmega do you think it is necessary to resize the toolbar for devices with safe area?

**Comment by lhr000lhrmega** [comment]
> @lhr000lhrmega do you think it is necessary to resize the toolbar for devices with the safe area?

4017BC30-4074-488F-AF72-657EC8E3E659

Technically, the overlapping problem should happen in all devices( no matter it has safe-area or not).
In fact, the bottom edge insert might have a flaw (causing a gap between the toolbar and scroll view) that leads the scroll view can't reach the bottom.
So, it would be better to create another Redmine ticket to fix this flaw and it's OK to resize the toolbar for all devices.

**Review by javitrujillo — APPROVED** [review]

**Pull request merged**
